app = 'laboratorio-prueva-red'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  # Le indicamos que NO apague la máquina de forma automática
  auto_stop_machines = 'stop'
  auto_start_machines = true
  # ¡Este es el truco! Obliga a que siempre haya 1 contenedor corriendo permanentemente
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
