app = 'laboratorio-prueva-red'
primary_region = 'dfw'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = [] # Dejar vacío para que no interfiera con los certificados de Fly
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
